package main

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/plumbing"
)

const (
	agentsDir    = "~/.agents"
	skillsDir    = agentsDir + "/skills"
	agentsSubDir = agentsDir + "/agents"
)

type SkillDownloader struct {
	baseDir string
}

type AgentDownloader struct {
	baseDir string
}

func NewSkillDownloader() *SkillDownloader {
	home, err := os.UserHomeDir()
	if err != nil {
		log.Fatal("Failed to get user home directory:", err)
	}

	baseDir := filepath.Join(home, ".agents", "skills")

	// Create base directory if it doesn't exist
	if err := os.MkdirAll(baseDir, 0755); err != nil {
		log.Fatal("Failed to create skills directory:", err)
	}

	return &SkillDownloader{baseDir: baseDir}
}

func NewAgentDownloader() *AgentDownloader {
	home, err := os.UserHomeDir()
	if err != nil {
		log.Fatal("Failed to get user home directory:", err)
	}

	baseDir := filepath.Join(home, ".agents", "agents")

	// Create base directory if it doesn't exist
	if err := os.MkdirAll(baseDir, 0755); err != nil {
		log.Fatal("Failed to create agents directory:", err)
	}

	return &AgentDownloader{baseDir: baseDir}
}

func (sd *SkillDownloader) parseRepoURL(repoURL string) (string, error) {
	repoURL = strings.TrimSpace(repoURL)

	// Handle GitHub shorthand (owner/repo)
	if !strings.Contains(repoURL, "/") {
		return "", fmt.Errorf("invalid repository format: %s", repoURL)
	}

	// If it's already a full URL, return as-is
	if strings.HasPrefix(repoURL, "http://") || strings.HasPrefix(repoURL, "https://") || strings.HasPrefix(repoURL, "git@") {
		return repoURL, nil
	}

	// Convert GitHub shorthand to full URL
	parts := strings.Split(repoURL, "/")
	if len(parts) != 2 {
		return "", fmt.Errorf("invalid GitHub shorthand format: %s (expected owner/repo)", repoURL)
	}

	return fmt.Sprintf("https://github.com/%s", repoURL), nil
}

func (sd *SkillDownloader) downloadSkill(repoURL, skillName string) error {
	fullURL, err := sd.parseRepoURL(repoURL)
	if err != nil {
		return err
	}

	// Create skill directory
	skillDir := filepath.Join(sd.baseDir, skillName)
	if err := os.MkdirAll(skillDir, 0755); err != nil {
		return fmt.Errorf("failed to create skill directory: %w", err)
	}

	// Clone repository
	repo, err := git.PlainClone(skillDir, false, &git.CloneOptions{
		URL:           fullURL,
		Depth:         1, // Shallow clone for efficiency
		ReferenceName: plumbing.HEAD,
		SingleBranch:  true,
	})
	if err != nil {
		// Clean up on failure
		os.RemoveAll(skillDir)
		return fmt.Errorf("failed to clone repository: %w", err)
	}

	// Get repository info for metadata
	ref, err := repo.Head()
	if err != nil {
		return fmt.Errorf("failed to get repository head: %w", err)
	}

	// Create metadata
	metadata := map[string]interface{}{
		"name":       skillName,
		"source":     fullURL,
		"commit":     ref.Hash().String(),
		"downloaded": "now",
	}

	// Save metadata file
	metadataFile := filepath.Join(skillDir, ".skill-metadata.json")
	if err := sd.saveMetadata(metadataFile, metadata); err != nil {
		log.Printf("Warning: failed to save metadata: %v", err)
	}

	// Create SKILL.md if it doesn't exist
	skillFile := filepath.Join(skillDir, "SKILL.md")
	if _, err := os.Stat(skillFile); os.IsNotExist(err) {
		if err := sd.createSkillFile(skillFile, skillName, fullURL); err != nil {
			log.Printf("Warning: failed to create SKILL.md: %v", err)
		}
	}

	fmt.Printf("Successfully downloaded skill '%s' from %s\n", skillName, fullURL)
	fmt.Printf("Skill stored in: %s\n", skillDir)

	return nil
}

func (sd *SkillDownloader) saveMetadata(filePath string, metadata map[string]interface{}) error {
	// Simple JSON marshaling for now
	content := fmt.Sprintf(`{
  "name": "%s",
  "source": "%s",
  "commit": "%s",
  "downloaded": "%s"
}`, metadata["name"], metadata["source"], metadata["commit"], metadata["downloaded"])

	return os.WriteFile(filePath, []byte(content), 0644)
}

func (sd *SkillDownloader) createSkillFile(filePath, skillName, source string) error {
	content := fmt.Sprintf(`# %s

Downloaded from: %s

## Description

This skill was automatically downloaded by Agent Smith.

## Usage

Add usage instructions here.

---
*Auto-generated by Agent Smith*
`, skillName, source)

	return os.WriteFile(filePath, []byte(content), 0644)
}

func (ad *AgentDownloader) parseRepoURL(repoURL string) (string, error) {
	repoURL = strings.TrimSpace(repoURL)

	// Handle GitHub shorthand (owner/repo)
	if !strings.Contains(repoURL, "/") {
		return "", fmt.Errorf("invalid repository format: %s", repoURL)
	}

	// If it's already a full URL, return as-is
	if strings.HasPrefix(repoURL, "http://") || strings.HasPrefix(repoURL, "https://") || strings.HasPrefix(repoURL, "git@") {
		return repoURL, nil
	}

	// Convert GitHub shorthand to full URL
	parts := strings.Split(repoURL, "/")
	if len(parts) != 2 {
		return "", fmt.Errorf("invalid GitHub shorthand format: %s (expected owner/repo)", repoURL)
	}

	return fmt.Sprintf("https://github.com/%s", repoURL), nil
}

func (ad *AgentDownloader) downloadAgent(repoURL, agentName string) error {
	fullURL, err := ad.parseRepoURL(repoURL)
	if err != nil {
		return err
	}

	// Create agent directory
	agentDir := filepath.Join(ad.baseDir, agentName)
	if err := os.MkdirAll(agentDir, 0755); err != nil {
		return fmt.Errorf("failed to create agent directory: %w", err)
	}

	// Clone repository
	repo, err := git.PlainClone(agentDir, false, &git.CloneOptions{
		URL:           fullURL,
		Depth:         1, // Shallow clone for efficiency
		ReferenceName: plumbing.HEAD,
		SingleBranch:  true,
	})
	if err != nil {
		// Clean up on failure
		os.RemoveAll(agentDir)
		return fmt.Errorf("failed to clone repository: %w", err)
	}

	// Get repository info for metadata
	ref, err := repo.Head()
	if err != nil {
		return fmt.Errorf("failed to get repository head: %w", err)
	}

	// Create metadata
	metadata := map[string]interface{}{
		"name":       agentName,
		"source":     fullURL,
		"commit":     ref.Hash().String(),
		"downloaded": "now",
	}

	// Save metadata file
	metadataFile := filepath.Join(agentDir, ".agent-lock.json")
	if err := ad.saveMetadata(metadataFile, metadata); err != nil {
		log.Printf("Warning: failed to save metadata: %v", err)
	}

	// Create AGENT.md if it doesn't exist
	agentFile := filepath.Join(agentDir, "AGENT.md")
	if _, err := os.Stat(agentFile); os.IsNotExist(err) {
		if err := ad.createAgentFile(agentFile, agentName, fullURL); err != nil {
			log.Printf("Warning: failed to create AGENT.md: %v", err)
		}
	}

	fmt.Printf("Successfully downloaded agent '%s' from %s\n", agentName, fullURL)
	fmt.Printf("Agent stored in: %s\n", agentDir)

	return nil
}

func (ad *AgentDownloader) saveMetadata(filePath string, metadata map[string]interface{}) error {
	// Simple JSON marshaling for now
	content := fmt.Sprintf(`{
  "name": "%s",
  "source": "%s",
  "commit": "%s",
  "downloaded": "%s"
}`, metadata["name"], metadata["source"], metadata["commit"], metadata["downloaded"])

	return os.WriteFile(filePath, []byte(content), 0644)
}

func (ad *AgentDownloader) createAgentFile(filePath, agentName, source string) error {
	content := fmt.Sprintf(`# %s

Downloaded from: %s

## Description

This agent was automatically downloaded by Agent Smith.

## Usage

Add usage instructions here.

---
*Auto-generated by Agent Smith*
`, agentName, source)

	return os.WriteFile(filePath, []byte(content), 0644)
}

func main() {
	if len(os.Args) < 3 {
		fmt.Println("Usage: agent-smith <command> <repository-url> <name>")
		fmt.Println("Commands:")
		fmt.Println("  add-skill  <repository-url> <skill-name>  Download a skill from a git repository")
		fmt.Println("  add-agent <repository-url> <agent-name>  Download an agent from a git repository")
		fmt.Println()
		fmt.Println("Examples:")
		fmt.Println("  agent-smith add-skill owner/repo my-skill")
		fmt.Println("  agent-smith add-skill https://github.com/owner/repo my-skill")
		fmt.Println("  agent-smith add-agent owner/repo my-agent")
		fmt.Println("  agent-smith add-agent https://github.com/owner/repo my-agent")
		os.Exit(1)
	}

	command := os.Args[1]
	repoURL := os.Args[2]
	name := os.Args[3]

	switch command {
	case "add-skill":
		downloader := NewSkillDownloader()
		if err := downloader.downloadSkill(repoURL, name); err != nil {
			log.Fatal("Failed to download skill:", err)
		}
	case "add-agent":
		downloader := NewAgentDownloader()
		if err := downloader.downloadAgent(repoURL, name); err != nil {
			log.Fatal("Failed to download agent:", err)
		}
	default:
		fmt.Printf("Unknown command: %s\n", command)
		fmt.Println("Supported commands: add-skill, add-agent")
		os.Exit(1)
	}
}
