package downloader

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/tjg184/agent-smith/internal/fileutil"
	"github.com/tjg184/agent-smith/internal/formatter"
	gitpkg "github.com/tjg184/agent-smith/internal/git"
	metadataPkg "github.com/tjg184/agent-smith/internal/metadata"
	"github.com/tjg184/agent-smith/internal/detector"
)

// baseDownloader holds the shared fields and provides common methods for all component downloaders.
type baseDownloader struct {
	baseDir   string
	detector  *detector.RepositoryDetector
	cloner    gitpkg.Cloner
	formatter *formatter.Formatter
}

func newBaseDownloader(baseDir string) baseDownloader {
	return baseDownloader{
		baseDir:   baseDir,
		detector:  detector.NewRepositoryDetector(),
		cloner:    gitpkg.NewDefaultCloner(),
		formatter: formatter.New(),
	}
}

func (b *baseDownloader) parseRepoURL(repoURL string) (string, error) {
	normalizedURL, err := b.detector.NormalizeURL(repoURL)
	if err != nil {
		return "", err
	}

	if err := b.detector.ValidateRepository(normalizedURL); err != nil {
		return "", fmt.Errorf("repository validation failed: %w", err)
	}

	return normalizedURL, nil
}

func (b *baseDownloader) saveLockFile(componentType, componentName, filesystemName, source, sourceType, sourceUrl, commitHash string, components int, detection, originalPath string) error {
	lockBaseDir := filepath.Dir(b.baseDir)

	if err := fileutil.CreateDirectoryWithPermissions(lockBaseDir); err != nil {
		return fmt.Errorf("failed to create lock file directory: %w", err)
	}

	var sourceHash, currentHash string
	componentDir := filepath.Join(b.baseDir, filesystemName)

	if hash, err := metadataPkg.ComputeLocalFolderHash(componentDir); err == nil {
		sourceHash = hash
		currentHash = hash
	} else {
		b.formatter.Warning("failed to compute hash: %v", err)
	}

	return metadataPkg.SaveComponentEntry(lockBaseDir, componentType, componentName, source, sourceType, sourceUrl, commitHash, originalPath, metadataPkg.ComponentEntryOptions{
		UpdatedAt:      "",
		Components:     components,
		Detection:      detection,
		SourceHash:     sourceHash,
		CurrentHash:    currentHash,
		FilesystemName: filesystemName,
	})
}

func (b *baseDownloader) detectSourceType(fullURL string) string {
	if strings.Contains(fullURL, "gitlab") {
		return "gitlab"
	}
	if strings.HasPrefix(fullURL, "git@") || strings.HasPrefix(fullURL, "ssh://") {
		return "git"
	}
	return "github"
}

func (b *baseDownloader) createComponentMarkdownFile(filePath, componentKind, componentName, source string) error {
	content := fmt.Sprintf("# %s\n\nDownloaded from: %s\n\n## Description\n\nThis %s was automatically downloaded by Agent Smith.\n\n## Usage\n\nAdd usage instructions here.\n\n---\n*Auto-generated by Agent Smith*\n", componentName, source, componentKind)
	return fileutil.CreateFileWithPermissions(filePath, []byte(content))
}

// DetermineDestinationFolderName determines the destination folder name, preserving any
// intermediate hierarchy between the component-type directory (skills/agents/commands) and
// the component file. For example:
//   - agents/category/my-agent.md      → category/my-agent
//   - skills/category/skill-name/SKILL.md → category/skill-name
//   - skills/skill-name/SKILL.md       → skill-name
func DetermineDestinationFolderName(componentFilePath string) string {
	componentTypeNames := []string{"skills", "agents", "commands"}

	fileName := filepath.Base(componentFilePath)
	fileExt := filepath.Ext(fileName)

	isSingleFile := fileExt == ".md" &&
		fileName != "SKILL.md" &&
		fileName != "AGENT.md" &&
		fileName != "COMMAND.md"

	// Start walking up from the file's directory (or the file itself for single-file components).
	// Collect all path segments until we hit a component-type directory.
	currentDir := filepath.Dir(componentFilePath)

	var segments []string

	if isSingleFile {
		segments = append(segments, strings.TrimSuffix(fileName, fileExt))
	}

	for {
		dirName := filepath.Base(currentDir)

		isComponentType := false
		for _, typeName := range componentTypeNames {
			if dirName == typeName {
				isComponentType = true
				break
			}
		}

		if isComponentType || dirName == "." || dirName == "" {
			break
		}

		segments = append(segments, dirName)

		parentDir := filepath.Dir(currentDir)

		if parentDir == currentDir || parentDir == "." || parentDir == "/" {
			break
		}

		currentDir = parentDir
	}

	if len(segments) == 0 {
		return "root"
	}

	// Segments were collected bottom-up (or with file stem prepended); reverse for top-down order.
	for i, j := 0, len(segments)-1; i < j; i, j = i+1, j-1 {
		segments[i], segments[j] = segments[j], segments[i]
	}

	return filepath.Join(segments...)
}

// extractGitHubOwnerRepo extracts "owner/repo" from a GitHub URL
// Returns empty string if not a GitHub URL or parsing fails
func extractGitHubOwnerRepo(url string) string {
	url = strings.TrimSpace(url)

	if strings.HasPrefix(url, "git@github.com:") {
		path := strings.TrimPrefix(url, "git@github.com:")
		path = strings.TrimSuffix(path, ".git")
		parts := strings.Split(path, "/")
		if len(parts) >= 2 {
			return parts[0] + "/" + parts[1]
		}
		return ""
	}

	if strings.Contains(url, "github.com/") {
		idx := strings.Index(url, "github.com/")
		path := url[idx+len("github.com/"):]
		path = strings.TrimSuffix(path, ".git")
		parts := strings.Split(path, "/")
		if len(parts) >= 2 {
			return parts[0] + "/" + parts[1]
		}
	}

	return ""
}
